<?php
use \Magento\Catalog\Block\Product\Widget\NewWidget;
use \MageOS\PageBuilderWidget\ViewModel\Adminhtml\ProductImagePreview;
/**
 * @var NewWidget $block
 * @var ProductImagePreview $productImagePreview
 */
$productImagePreview = $block->getData('viewModel');
?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()) :?>
    <?= $block->getChildHtml("previewAssets"); ?>
    <div class="block widget block-new-products-images">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('New Products')) ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-new-products-<?= $block->escapeHtmlAttr($suffix) ?>"
                class="product-items product-items-images">
                <?php foreach ($_products->getItems() as $_product) :?>
                    <li class="product-item">
                        <a class="product-item-photo" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           title="<?= /* @noEscape */ $block->stripTags($_product->getName(), null, true) ?>">
                            <?php /* new_products_images_only_widget */ ?>
                            <img src="<?= $productImagePreview->getProductImage($_product) ?>" width="75" height="75" />
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
